### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by zhkostadinov** [sridharbandi/Selenium-Python-Template#1]
When I ran the code with displayed command in the readme.md, the following error is displayed:
Traceback (most recent call last):
  File "tests/RunTest.py", line 4, in <module>
    from driverutil.Browser import Browser
ModuleNotFoundError: No module named 'driverutil'

Any suggestion, how can i fix it?

**Comment by sridharbandi** [comment]
Hi, Are you still facing the issue? Have you installed the requirements?

**Comment by chaitanya1** [comment]
Even after installing the dependencies also showing the above error.

**Comment by sridharbandi** [comment]
PYTHONPATH need to be set. Refer https://bic-berkeley.github.io/psych-214-fall-2016/using_pythonpath.html.

**Comment by sridharbandi** [comment]
> Even after installing the dependencies also showing the above error.

PYTHONPATH need to be set. Refer https://bic-berkeley.github.io/psych-214-fall-2016/using_pythonpath.html.
